// <auto-generated />
using System;
using InterviewPrep.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewPrep.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InterviewPrepDbContext))]
    [Migration("20260711123453_TurkishSeedLocalization")]
    partial class TurkishSeedLocalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("InterviewPrep.Domain.Entities.CodingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeSolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArchitectureScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BestPracticesFeedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CodingQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectnessScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowUpQuestions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InterviewFeedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadabilityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeniorLevelImprovements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAtUtc");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("CodingQuestionId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("CodingAttempts");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.CodingQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedSolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StarterCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CodingQuestions");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.CodingQuestionTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CodingQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("CodingQuestionId", "TagId")
                        .IsUnique();

                    b.ToTable("CodingQuestionTag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextReviewAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextReviewAtUtc");

                    b.HasIndex("TopicId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.FlashcardTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("FlashcardId", "TagId")
                        .IsUnique();

                    b.ToTable("FlashcardTag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.InterviewAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpQuestions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StructureScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechnicalAccuracyScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("InterviewSessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("InterviewAnswers");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.InterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommunicationScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("StructureScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryFeedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnicalAccuracyScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiExplanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiImprovementSuggestions")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("IsPinned", "UpdatedAtUtc");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.NoteTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("NoteId", "TagId")
                        .IsUnique();

                    b.ToTable("NoteTag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.NoteVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("NoteId", "Version")
                        .IsUnique();

                    b.ToTable("NoteVersions");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.ProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivityDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodingAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutesStudied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MockInterviews")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsSolved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityDateUtc");

                    b.HasIndex("TopicId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("ProgressEntries");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.StudyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActualMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledForUtc");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.StudyPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("StudyPlanId", "SortOrder")
                        .IsUnique();

                    b.ToTable("StudyPlanItems");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.SystemDesignScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiCritique")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiDesign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caching")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Constraints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logging")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageQueue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Monitoring")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scalability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Security")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("SystemDesignScenarios");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.SystemDesignScenarioTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SystemDesignScenarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("SystemDesignScenarioId", "TagId")
                        .IsUnique();

                    b.ToTable("SystemDesignScenarioTag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedMastery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("Topics", t =>
                        {
                            t.HasCheckConstraint("CK_Topics_Confidence", "ConfidenceLevel >= 0 AND ConfidenceLevel <= 100");

                            t.HasCheckConstraint("CK_Topics_Mastery", "EstimatedMastery >= 0 AND EstimatedMastery <= 100");

                            t.HasCheckConstraint("CK_Topics_Progress", "Progress >= 0 AND Progress <= 100");
                        });
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.TopicTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("TopicId", "TagId")
                        .IsUnique();

                    b.ToTable("TopicTag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.CodingAttempt", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.CodingQuestion", "CodingQuestion")
                        .WithMany("Attempts")
                        .HasForeignKey("CodingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodingQuestion");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.CodingQuestion", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Topic", "Topic")
                        .WithMany("CodingQuestions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.CodingQuestionTag", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.CodingQuestion", "CodingQuestion")
                        .WithMany("CodingQuestionTags")
                        .HasForeignKey("CodingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrep.Domain.Entities.Tag", "Tag")
                        .WithMany("CodingQuestionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodingQuestion");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Flashcard", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Topic", "Topic")
                        .WithMany("Flashcards")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.FlashcardTag", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Flashcard", "Flashcard")
                        .WithMany("FlashcardTags")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrep.Domain.Entities.Tag", "Tag")
                        .WithMany("FlashcardTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.InterviewAnswer", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.InterviewSession", "InterviewSession")
                        .WithMany("Answers")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Note", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Topic", "Topic")
                        .WithMany("Notes")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.NoteTag", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrep.Domain.Entities.Tag", "Tag")
                        .WithMany("NoteTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.NoteVersion", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Note", "Note")
                        .WithMany("Versions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.ProgressEntry", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Topic", "Topic")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.StudyPlanItem", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.StudyPlan", "StudyPlan")
                        .WithMany("Items")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrep.Domain.Entities.Topic", "Topic")
                        .WithMany("StudyPlanItems")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StudyPlan");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.SystemDesignScenario", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Topic", "Topic")
                        .WithMany("SystemDesignScenarios")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.SystemDesignScenarioTag", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.SystemDesignScenario", "SystemDesignScenario")
                        .WithMany("SystemDesignScenarioTags")
                        .HasForeignKey("SystemDesignScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrep.Domain.Entities.Tag", "Tag")
                        .WithMany("SystemDesignScenarioTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemDesignScenario");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.TopicTag", b =>
                {
                    b.HasOne("InterviewPrep.Domain.Entities.Tag", "Tag")
                        .WithMany("TopicTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewPrep.Domain.Entities.Topic", "Topic")
                        .WithMany("TopicTags")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.CodingQuestion", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("CodingQuestionTags");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Flashcard", b =>
                {
                    b.Navigation("FlashcardTags");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.InterviewSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Note", b =>
                {
                    b.Navigation("NoteTags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.StudyPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.SystemDesignScenario", b =>
                {
                    b.Navigation("SystemDesignScenarioTags");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Tag", b =>
                {
                    b.Navigation("CodingQuestionTags");

                    b.Navigation("FlashcardTags");

                    b.Navigation("NoteTags");

                    b.Navigation("SystemDesignScenarioTags");

                    b.Navigation("TopicTags");
                });

            modelBuilder.Entity("InterviewPrep.Domain.Entities.Topic", b =>
                {
                    b.Navigation("CodingQuestions");

                    b.Navigation("Flashcards");

                    b.Navigation("Notes");

                    b.Navigation("ProgressEntries");

                    b.Navigation("StudyPlanItems");

                    b.Navigation("SystemDesignScenarios");

                    b.Navigation("TopicTags");
                });
#pragma warning restore 612, 618
        }
    }
}
